/** Metadata of a page during the build. */
interface Page {
  /** Relative path of the source file (e.g. "pages/about.tulip") */
  path: string;
  /** Output slug (e.g. "about.html") */
  slug: string;
  /** Parsed frontmatter from markdown (empty for .tulip) */
  frontmatter: Record<string, string>;
}

/** Build context — access to site config and pages. */
interface BuildContext {
  /** Variables from [site] in tulip.toml */
  site: { name: string; base_url: string; description: string };
  /** All pages that will be generated */
  pages: Page[];
  /** Output directory (e.g. "dist") */
  outputDir: string;
  /** Project directory */
  projectDir: string;
}

/** A page generated by a plugin. */
interface GeneratedPage {
  /** Output path relative to outputDir (e.g. "feed.xml") */
  path: string;
  /** File content */
  content: string;
}

/** Plugin config from tulip.toml. */
type PluginConfig = Record<string, unknown>;

/** tulip plugin contract. All hooks are optional. */
interface TulipPlugin {
  name: string;

  /** Plugin config from tulip.toml — injected automatically. */
  config?: PluginConfig;

  /** Called when the plugin is loaded. */
  setup?(config: PluginConfig): void;

  /** Before the build starts. */
  beforeBuild?(ctx: BuildContext): void;

  /** Transform markdown before rendering to HTML. */
  transformMarkdown?(content: string, page: Page): string;

  /** Modify the variable context before rendering a page. */
  transformContext?(ctx: Record<string, unknown>, page: Page): Record<string, unknown>;

  /** Transform page HTML after rendering. */
  transformHtml?(html: string, page: Page): string;

  /** Generate new pages (RSS, sitemap, etc). */
  generatePages?(ctx: BuildContext): GeneratedPage[];

  /** Return tags to inject into <head>. */
  head?(): HeadTag[];

  /** After the build completes. */
  afterBuild?(ctx: BuildContext): void;
}

/** A tag to inject into <head>. */
interface HeadTag {
  tag: string;
  attrs?: Record<string, string | boolean>;
}
